proxy:
  #  build: .
  image: akakum/identiproxy
  links:
    - identidock
  ports:
    - 80:80
  environment:
    - NGINX_HOST=172.17.0.7
    - NGINX_PROXY=http://identidock:9090
identidock:
  image: akakum/identidock
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD
dnmonster:
  image: amouat/dnmonster
redis:
  image: redis
logspout:
  image: amouat/logspout-logstash
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - 8000:80
  links:
    - logstash
  environment:
    # ROUTE_URIS: logstash+tcp://logstash:5000
    ROUTE_URIS: logstash://logstash:5000
    #command: logstash://logstash:5000
logstash:
  image: logstash:8.2.0
  
  restart: always
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  ports:
    - 5000:5000
  environment:
    LOGSPOUT: ignore
  links:
    - elasticsearch
  command: -f /etc/logstash.conf

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
  
  restart: always
  environment:
    LOGSPOUT: ignore

kibana:
  image: docker.elastic.co/kibana/kibana:8.2.0
  environment:
    LOGSPOUT: ignore
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - 5601:5601



    


