proxy:
  #  build: .
  image: akakum/identiproxy
  links:
    - identidock
  ports:
    - 80:80
  environment:
    - NGINX_HOST=172.17.0.5
    - NGINX_PROXY=http://identidock:9090
identidock:
  image: akakum/identidock
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD
dnmonster:
  image: amouat/dnmonster
redis:
  image: redis


